--- 005a_create_reservation_reference_tables
BEGIN;

CREATE TABLE inventory.reservation_statuses (
    status_code varchar(30) PRIMARY KEY,
    display_name varchar(50) NOT NULL,
    description text,
    holds_inventory boolean NOT NULL,
    is_terminal boolean NOT NULL,
    sort_order smallint NOT NULL,

    CONSTRAINT reservation_statuses_status_code_format
        CHECK (
            status_code = lower(status_code)
            AND status_code ~ '^[a-z][a-z0-9_]*$'
        ),

    CONSTRAINT reservation_statuses_display_name_not_blank
        CHECK (btrim(display_name) <> ''),

    CONSTRAINT reservation_statuses_sort_order_positive
        CHECK (sort_order > 0),

    CONSTRAINT reservation_statuses_sort_order_unique
        UNIQUE (sort_order)
);


CREATE TABLE inventory.reservation_source_types (
    source_type_code varchar(40) PRIMARY KEY,
    display_name varchar(75) NOT NULL,
    description text,
    requires_source_id boolean NOT NULL DEFAULT true,
    requires_source_line_id boolean NOT NULL DEFAULT false,
    is_active boolean NOT NULL DEFAULT true,
    sort_order smallint NOT NULL,

    CONSTRAINT reservation_source_types_code_format
        CHECK (
            source_type_code = lower(source_type_code)
            AND source_type_code ~ '^[a-z][a-z0-9_]*$'
        ),

    CONSTRAINT reservation_source_types_display_name_not_blank
        CHECK (btrim(display_name) <> ''),

    CONSTRAINT reservation_source_types_sort_order_positive
        CHECK (sort_order > 0),

    CONSTRAINT reservation_source_types_sort_order_unique
        UNIQUE (sort_order)
);


INSERT INTO inventory.reservation_statuses (
    status_code,
    display_name,
    description,
    holds_inventory,
    is_terminal,
    sort_order
)
VALUES
    (
        'active',
        'Active',
        'Inventory is currently reserved and unavailable for other operations.',
        true,
        false,
        10
    ),
    (
        'fulfilled',
        'Fulfilled',
        'The reservation was completed and the inventory was consumed.',
        false,
        true,
        20
    ),
    (
        'released',
        'Released',
        'The reserved inventory was intentionally returned to availability.',
        false,
        true,
        30
    ),
    (
        'cancelled',
        'Cancelled',
        'The originating request was cancelled before fulfillment.',
        false,
        true,
        40
    ),
    (
        'expired',
        'Expired',
        'The reservation expired before fulfillment.',
        false,
        true,
        50
    )
ON CONFLICT (status_code) DO NOTHING;


INSERT INTO inventory.reservation_source_types (
    source_type_code,
    display_name,
    description,
    requires_source_id,
    requires_source_line_id,
    is_active,
    sort_order
)
VALUES
    (
        'sales_order',
        'Sales Order',
        'Inventory reserved for a sales order or sales order item.',
        true,
        true,
        true,
        10
    ),
    (
        'booking',
        'Booking',
        'Inventory reserved for a booking or booking item.',
        true,
        false,
        true,
        20
    ),
    (
        'warehouse_transfer',
        'Warehouse Transfer',
        'Inventory reserved for movement between warehouses.',
        true,
        false,
        true,
        30
    ),
    (
        'manual',
        'Manual Hold',
        'Inventory reserved manually without a required originating document.',
        false,
        false,
        true,
        40
    )
ON CONFLICT (source_type_code) DO NOTHING;

COMMIT;

--------------------------------------------
-------005b_create_inventory_reservations
--------------------------------------------

BEGIN;

CREATE SEQUENCE inventory.reservation_code_seq
    AS bigint
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    NO MAXVALUE
    CACHE 20;


CREATE OR REPLACE FUNCTION inventory.generate_reservation_code()
RETURNS varchar
LANGUAGE sql
VOLATILE
AS $$
    SELECT
        'RSV-' ||
        lpad(
            nextval('inventory.reservation_code_seq')::text,
            9,
            '0'
        );
$$;


CREATE TABLE inventory.reservations (
    reservation_id bigint
        GENERATED BY DEFAULT AS IDENTITY,

    reservation_code varchar(20)
        NOT NULL
        DEFAULT inventory.generate_reservation_code(),

    warehouse_inventory_id integer NOT NULL,

    quantity integer NOT NULL,

    status_code varchar(30)
        NOT NULL
        DEFAULT 'active',

    source_type_code varchar(40) NOT NULL,

    source_id bigint,
    source_line_id bigint,

    expires_at timestamp without time zone,

    fulfilled_at timestamp without time zone,
    released_at timestamp without time zone,
    cancelled_at timestamp without time zone,
    expired_at timestamp without time zone,

    created_at timestamp without time zone
        NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    updated_at timestamp without time zone
        NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT reservations_pkey
        PRIMARY KEY (reservation_id),

    CONSTRAINT reservations_reservation_code_unique
        UNIQUE (reservation_code),

    CONSTRAINT reservations_warehouse_inventory_fkey
        FOREIGN KEY (warehouse_inventory_id)
        REFERENCES public.warehouse_inventory (warehouse_inventory_id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT reservations_status_code_fkey
        FOREIGN KEY (status_code)
        REFERENCES inventory.reservation_statuses (status_code)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT reservations_source_type_code_fkey
        FOREIGN KEY (source_type_code)
        REFERENCES inventory.reservation_source_types (source_type_code)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT reservations_reservation_code_format
        CHECK (
            reservation_code ~ '^RSV-[0-9]{9}$'
        ),

    CONSTRAINT reservations_quantity_positive
        CHECK (quantity > 0),

    CONSTRAINT reservations_source_id_positive
        CHECK (
            source_id IS NULL
            OR source_id > 0
        ),

    CONSTRAINT reservations_source_line_id_positive
        CHECK (
            source_line_id IS NULL
            OR source_line_id > 0
        ),

    CONSTRAINT reservations_expiration_after_creation
        CHECK (
            expires_at IS NULL
            OR expires_at > created_at
        ),

    CONSTRAINT reservations_updated_not_before_created
        CHECK (
            updated_at >= created_at
        ),

    CONSTRAINT reservations_fulfilled_not_before_created
        CHECK (
            fulfilled_at IS NULL
            OR fulfilled_at >= created_at
        ),

    CONSTRAINT reservations_released_not_before_created
        CHECK (
            released_at IS NULL
            OR released_at >= created_at
        ),

    CONSTRAINT reservations_cancelled_not_before_created
        CHECK (
            cancelled_at IS NULL
            OR cancelled_at >= created_at
        ),

    CONSTRAINT reservations_expired_not_before_created
        CHECK (
            expired_at IS NULL
            OR expired_at >= created_at
        ),

    CONSTRAINT reservations_single_terminal_timestamp
        CHECK (
            num_nonnulls(
                fulfilled_at,
                released_at,
                cancelled_at,
                expired_at
            ) <= 1
        ),

    CONSTRAINT reservations_status_timestamp_consistency
        CHECK (
            (
                status_code = 'active'
                AND fulfilled_at IS NULL
                AND released_at IS NULL
                AND cancelled_at IS NULL
                AND expired_at IS NULL
            )
            OR
            (
                status_code = 'fulfilled'
                AND fulfilled_at IS NOT NULL
                AND released_at IS NULL
                AND cancelled_at IS NULL
                AND expired_at IS NULL
            )
            OR
            (
                status_code = 'released'
                AND fulfilled_at IS NULL
                AND released_at IS NOT NULL
                AND cancelled_at IS NULL
                AND expired_at IS NULL
            )
            OR
            (
                status_code = 'cancelled'
                AND fulfilled_at IS NULL
                AND released_at IS NULL
                AND cancelled_at IS NOT NULL
                AND expired_at IS NULL
            )
            OR
            (
                status_code = 'expired'
                AND fulfilled_at IS NULL
                AND released_at IS NULL
                AND cancelled_at IS NULL
                AND expired_at IS NOT NULL
            )
        )
);


CREATE INDEX reservations_warehouse_inventory_idx
    ON inventory.reservations (warehouse_inventory_id);


CREATE INDEX reservations_active_inventory_idx
    ON inventory.reservations (warehouse_inventory_id)
    WHERE status_code = 'active';


CREATE INDEX reservations_source_reference_idx
    ON inventory.reservations (
        source_type_code,
        source_id,
        source_line_id
    );


CREATE INDEX reservations_active_expiration_idx
    ON inventory.reservations (expires_at)
    WHERE status_code = 'active'
      AND expires_at IS NOT NULL;


COMMIT;

------------------------------------------
-------005c_create_reservation_events
------------------------------------------

BEGIN;

CREATE TABLE inventory.reservation_events (
    reservation_event_id bigint
        GENERATED BY DEFAULT AS IDENTITY,

    reservation_id bigint NOT NULL,

    event_type varchar(40) NOT NULL,

    previous_status_code varchar(30),
    new_status_code varchar(30),

    previous_quantity integer,
    new_quantity integer,

    reason text,
    metadata jsonb,

    created_at timestamp without time zone
        NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT reservation_events_pkey
        PRIMARY KEY (reservation_event_id),

    CONSTRAINT reservation_events_reservation_id_fkey
        FOREIGN KEY (reservation_id)
        REFERENCES inventory.reservations (reservation_id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT reservation_events_previous_status_fkey
        FOREIGN KEY (previous_status_code)
        REFERENCES inventory.reservation_statuses (status_code)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT reservation_events_new_status_fkey
        FOREIGN KEY (new_status_code)
        REFERENCES inventory.reservation_statuses (status_code)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT reservation_events_event_type_not_blank
        CHECK (btrim(event_type) <> ''),

    CONSTRAINT reservation_events_event_type_format
        CHECK (
            event_type = lower(event_type)
            AND event_type ~ '^[a-z][a-z0-9_]*$'
        ),

    CONSTRAINT reservation_events_previous_quantity_positive
        CHECK (
            previous_quantity IS NULL
            OR previous_quantity > 0
        ),

    CONSTRAINT reservation_events_new_quantity_positive
        CHECK (
            new_quantity IS NULL
            OR new_quantity > 0
        ),

    CONSTRAINT reservation_events_reason_not_blank
        CHECK (
            reason IS NULL
            OR btrim(reason) <> ''
        ),

    CONSTRAINT reservation_events_created_values_required
        CHECK (
            event_type <> 'created'
            OR (
                previous_status_code IS NULL
                AND new_status_code = 'active'
                AND previous_quantity IS NULL
                AND new_quantity IS NOT NULL
            )
        ),

    CONSTRAINT reservation_events_status_change_values_required
        CHECK (
            event_type NOT IN (
                'fulfilled',
                'released',
                'cancelled',
                'expired'
            )
            OR (
                previous_status_code = 'active'
                AND new_status_code = event_type
            )
        ),

    CONSTRAINT reservation_events_quantity_adjusted_values_required
        CHECK (
            event_type <> 'quantity_adjusted'
            OR (
                previous_quantity IS NOT NULL
                AND new_quantity IS NOT NULL
                AND previous_quantity <> new_quantity
            )
        )
);


CREATE INDEX reservation_events_reservation_created_idx
    ON inventory.reservation_events (
        reservation_id,
        created_at,
        reservation_event_id
    );


CREATE INDEX reservation_events_event_type_idx
    ON inventory.reservation_events (event_type);


CREATE INDEX reservation_events_metadata_gin_idx
    ON inventory.reservation_events
    USING gin (metadata)
    WHERE metadata IS NOT NULL;

COMMIT;

------------------------------------------------------
-------005d_add_reservation_user_audit
------------------------------------------------------
BEGIN;

ALTER TABLE inventory.reservations
ADD COLUMN created_by_user_id integer;

ALTER TABLE inventory.reservations
ADD CONSTRAINT reservations_created_by_user_fkey
FOREIGN KEY (created_by_user_id)
REFERENCES public.users (user_id)
ON UPDATE RESTRICT
ON DELETE RESTRICT;


ALTER TABLE inventory.reservation_events
ADD COLUMN performed_by_user_id integer;

ALTER TABLE inventory.reservation_events
ADD CONSTRAINT reservation_events_performed_by_user_fkey
FOREIGN KEY (performed_by_user_id)
REFERENCES public.users (user_id)
ON UPDATE RESTRICT
ON DELETE RESTRICT;


CREATE INDEX reservations_created_by_user_idx
ON inventory.reservations (created_by_user_id);


CREATE INDEX reservation_events_performed_by_user_idx
ON inventory.reservation_events (performed_by_user_id);

COMMIT;

-----------------------------------------------------------
-----------005e_create_reservation_function
-----------------------------------------------------------
BEGIN;

CREATE OR REPLACE FUNCTION inventory.create_reservation(
    p_warehouse_inventory_id integer,
    p_quantity integer,
    p_source_type_code varchar,
    p_source_id bigint DEFAULT NULL,
    p_source_line_id bigint DEFAULT NULL,
    p_expires_at timestamp without time zone DEFAULT NULL,
    p_created_by_user_id integer DEFAULT NULL,
    p_reason text DEFAULT NULL,
    p_metadata jsonb DEFAULT NULL
)
RETURNS inventory.reservations
LANGUAGE plpgsql
AS $$
DECLARE
    v_quantity_on_hand integer;
    v_quantity_reserved integer;
    v_quantity_available integer;

    v_requires_source_id boolean;
    v_requires_source_line_id boolean;
    v_source_type_active boolean;

    v_reservation inventory.reservations%ROWTYPE;
BEGIN
    /*
     * Validate the basic request.
     */
    IF p_warehouse_inventory_id IS NULL THEN
        RAISE EXCEPTION
            'warehouse_inventory_id is required'
            USING ERRCODE = '22004';
    END IF;

    IF p_quantity IS NULL OR p_quantity <= 0 THEN
        RAISE EXCEPTION
            'Reservation quantity must be greater than zero'
            USING ERRCODE = '22023';
    END IF;

    IF p_source_type_code IS NULL
       OR btrim(p_source_type_code) = '' THEN
        RAISE EXCEPTION
            'source_type_code is required'
            USING ERRCODE = '22023';
    END IF;

    IF p_source_id IS NOT NULL AND p_source_id <= 0 THEN
        RAISE EXCEPTION
            'source_id must be greater than zero when supplied'
            USING ERRCODE = '22023';
    END IF;

    IF p_source_line_id IS NOT NULL
       AND p_source_line_id <= 0 THEN
        RAISE EXCEPTION
            'source_line_id must be greater than zero when supplied'
            USING ERRCODE = '22023';
    END IF;

    IF p_expires_at IS NOT NULL
       AND p_expires_at <= CURRENT_TIMESTAMP THEN
        RAISE EXCEPTION
            'expires_at must be later than the current timestamp'
            USING ERRCODE = '22023';
    END IF;

    IF p_reason IS NOT NULL
       AND btrim(p_reason) = '' THEN
        RAISE EXCEPTION
            'reason cannot be blank when supplied'
            USING ERRCODE = '22023';
    END IF;

    /*
     * Validate the source type and determine which identifiers it requires.
     */
    SELECT
        requires_source_id,
        requires_source_line_id,
        is_active
    INTO
        v_requires_source_id,
        v_requires_source_line_id,
        v_source_type_active
    FROM inventory.reservation_source_types
    WHERE source_type_code = lower(btrim(p_source_type_code));

    IF NOT FOUND THEN
        RAISE EXCEPTION
            'Unknown reservation source type: %',
            p_source_type_code
            USING ERRCODE = '22023';
    END IF;

    IF NOT v_source_type_active THEN
        RAISE EXCEPTION
            'Reservation source type % is inactive',
            p_source_type_code
            USING ERRCODE = '22023';
    END IF;

    IF v_requires_source_id
       AND p_source_id IS NULL THEN
        RAISE EXCEPTION
            'Source type % requires source_id',
            p_source_type_code
            USING ERRCODE = '22023';
    END IF;

    IF v_requires_source_line_id
       AND p_source_line_id IS NULL THEN
        RAISE EXCEPTION
            'Source type % requires source_line_id',
            p_source_type_code
            USING ERRCODE = '22023';
    END IF;

    /*
     * Lock the inventory row.
     *
     * Concurrent reservation requests for the same row must wait here,
     * preventing both transactions from reserving the same availability.
     */
    SELECT
        quantity_on_hand,
        quantity_reserved
    INTO
        v_quantity_on_hand,
        v_quantity_reserved
    FROM public.warehouse_inventory
    WHERE warehouse_inventory_id = p_warehouse_inventory_id
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION
            'Warehouse inventory record % does not exist',
            p_warehouse_inventory_id
            USING ERRCODE = 'P0002';
    END IF;

    v_quantity_available :=
        v_quantity_on_hand - v_quantity_reserved;

    IF p_quantity > v_quantity_available THEN
        RAISE EXCEPTION
            'Insufficient inventory for warehouse_inventory_id %. Requested: %, available: %',
            p_warehouse_inventory_id,
            p_quantity,
            v_quantity_available
            USING ERRCODE = 'P0001';
    END IF;

    /*
     * Create the detailed reservation record.
     */
    INSERT INTO inventory.reservations (
        warehouse_inventory_id,
        quantity,
        status_code,
        source_type_code,
        source_id,
        source_line_id,
        expires_at,
        created_by_user_id
    )
    VALUES (
        p_warehouse_inventory_id,
        p_quantity,
        'active',
        lower(btrim(p_source_type_code)),
        p_source_id,
        p_source_line_id,
        p_expires_at,
        p_created_by_user_id
    )
    RETURNING *
    INTO v_reservation;

    /*
     * Update the fast current inventory balance.
     */
    UPDATE public.warehouse_inventory
    SET
        quantity_reserved = quantity_reserved + p_quantity,
        updated_at = CURRENT_TIMESTAMP
    WHERE warehouse_inventory_id = p_warehouse_inventory_id;

    /*
     * Append the immutable creation event.
     */
    INSERT INTO inventory.reservation_events (
        reservation_id,
        event_type,
        previous_status_code,
        new_status_code,
        previous_quantity,
        new_quantity,
        reason,
        metadata,
        performed_by_user_id
    )
    VALUES (
        v_reservation.reservation_id,
        'created',
        NULL,
        'active',
        NULL,
        p_quantity,
        p_reason,
        p_metadata,
        p_created_by_user_id
    );

    RETURN v_reservation;
END;
$$;

COMMIT;
--------------------------------------------
------005f_release_reservation_function
--------------------------------------------
BEGIN;

CREATE OR REPLACE FUNCTION inventory.release_reservation(
    p_reservation_id bigint,
    p_performed_by_user_id integer DEFAULT NULL,
    p_reason text DEFAULT NULL,
    p_metadata jsonb DEFAULT NULL
)
RETURNS inventory.reservations
LANGUAGE plpgsql
AS $$
DECLARE
    v_reservation inventory.reservations%ROWTYPE;
    v_updated_reservation inventory.reservations%ROWTYPE;
    v_current_quantity_reserved integer;
BEGIN
    /*
     * Validate the request.
     */
    IF p_reservation_id IS NULL THEN
        RAISE EXCEPTION
            'reservation_id is required'
            USING ERRCODE = '22004';
    END IF;

    IF p_reservation_id <= 0 THEN
        RAISE EXCEPTION
            'reservation_id must be greater than zero'
            USING ERRCODE = '22023';
    END IF;

    IF p_reason IS NOT NULL
       AND btrim(p_reason) = '' THEN
        RAISE EXCEPTION
            'reason cannot be blank when supplied'
            USING ERRCODE = '22023';
    END IF;

    /*
     * Lock the reservation so two sessions cannot release or otherwise
     * complete the same reservation simultaneously.
     */
    SELECT *
    INTO v_reservation
    FROM inventory.reservations
    WHERE reservation_id = p_reservation_id
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION
            'Reservation % does not exist',
            p_reservation_id
            USING ERRCODE = 'P0002';
    END IF;

    IF v_reservation.status_code <> 'active' THEN
        RAISE EXCEPTION
            'Reservation % cannot be released because its current status is %',
            p_reservation_id,
            v_reservation.status_code
            USING ERRCODE = 'P0001';
    END IF;

    /*
     * Lock the related inventory balance.
     */
    SELECT quantity_reserved
    INTO v_current_quantity_reserved
    FROM public.warehouse_inventory
    WHERE warehouse_inventory_id =
        v_reservation.warehouse_inventory_id
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION
            'Warehouse inventory record % does not exist',
            v_reservation.warehouse_inventory_id
            USING ERRCODE = 'P0002';
    END IF;

    /*
     * This should never fail during normal operation. It protects against
     * existing balance drift or uncontrolled direct updates.
     */
    IF v_current_quantity_reserved < v_reservation.quantity THEN
        RAISE EXCEPTION
            'Reserved inventory balance is inconsistent for warehouse_inventory_id %. Balance: %, reservation quantity: %',
            v_reservation.warehouse_inventory_id,
            v_current_quantity_reserved,
            v_reservation.quantity
            USING ERRCODE = 'P0001';
    END IF;

    /*
     * Return the reserved quantity to availability.
     */
    UPDATE public.warehouse_inventory
    SET
        quantity_reserved =
            quantity_reserved - v_reservation.quantity,
        updated_at = CURRENT_TIMESTAMP
    WHERE warehouse_inventory_id =
        v_reservation.warehouse_inventory_id;

    /*
     * Move the reservation into its terminal released state.
     */
    UPDATE inventory.reservations
    SET
        status_code = 'released',
        released_at = CURRENT_TIMESTAMP,
        updated_at = CURRENT_TIMESTAMP
    WHERE reservation_id = p_reservation_id
    RETURNING *
    INTO v_updated_reservation;

    /*
     * Append the audit event.
     */
    INSERT INTO inventory.reservation_events (
        reservation_id,
        event_type,
        previous_status_code,
        new_status_code,
        previous_quantity,
        new_quantity,
        reason,
        metadata,
        performed_by_user_id
    )
    VALUES (
        p_reservation_id,
        'released',
        'active',
        'released',
        v_reservation.quantity,
        v_reservation.quantity,
        p_reason,
        p_metadata,
        p_performed_by_user_id
    );

    RETURN v_updated_reservation;
END;
$$;

COMMIT;

---------------------------------------------------------
-----005g_create_reservation_test_reset_procedure.sql
---------------------------------------------------------
BEGIN;

CREATE OR REPLACE PROCEDURE inventory.reset_reservation_test_data(
    p_confirmation text
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_reservation_id_sequence text;
    v_event_id_sequence text;
BEGIN
    /*
     * Require an explicit confirmation phrase because this operation
     * permanently deletes all reservation records and events.
     */
    IF p_confirmation IS DISTINCT FROM 'RESET RESERVATION TEST DATA' THEN
        RAISE EXCEPTION
            'Reset rejected. Pass the exact confirmation phrase: RESET RESERVATION TEST DATA'
            USING ERRCODE = '22023';
    END IF;

    /*
     * Lock the affected tables so another session cannot create or modify
     * reservations while the reset is running.
     */
    LOCK TABLE inventory.reservation_events
        IN ACCESS EXCLUSIVE MODE;

    LOCK TABLE inventory.reservations
        IN ACCESS EXCLUSIVE MODE;

    LOCK TABLE public.warehouse_inventory
        IN ACCESS EXCLUSIVE MODE;

    /*
     * Delete children before parents because reservation_events has a
     * foreign key to reservations.
     */
    DELETE FROM inventory.reservation_events;

    DELETE FROM inventory.reservations;

    /*
     * Restore the cached reserved balance to a clean test baseline.
     */
    UPDATE public.warehouse_inventory
    SET
        quantity_reserved = 0,
        updated_at = CURRENT_TIMESTAMP
    WHERE quantity_reserved <> 0;

    /*
     * Locate the identity sequences generated for the primary keys.
     */
    v_reservation_id_sequence :=
        pg_get_serial_sequence(
            'inventory.reservations',
            'reservation_id'
        );

    v_event_id_sequence :=
        pg_get_serial_sequence(
            'inventory.reservation_events',
            'reservation_event_id'
        );

    /*
     * Reset identity values so the next generated value is 1.
     */
    IF v_reservation_id_sequence IS NOT NULL THEN
        PERFORM setval(
            v_reservation_id_sequence::regclass,
            1,
            false
        );
    END IF;

    IF v_event_id_sequence IS NOT NULL THEN
        PERFORM setval(
            v_event_id_sequence::regclass,
            1,
            false
        );
    END IF;

    /*
     * Reset the separate human-readable reservation-code sequence.
     */
    PERFORM setval(
        'inventory.reservation_code_seq'::regclass,
        1,
        false
    );

    RAISE NOTICE
        'Reservation test data reset successfully.';
END;
$$;

COMMIT;

--------------------------------------------------------
------005h_fulfill_reservation_function
---------------------------------------------------------
BEGIN;

CREATE OR REPLACE FUNCTION inventory.fulfill_reservation(
    p_reservation_id bigint,
    p_performed_by_user_id integer DEFAULT NULL,
    p_reason text DEFAULT NULL,
    p_metadata jsonb DEFAULT NULL
)
RETURNS inventory.reservations
LANGUAGE plpgsql
AS $$
DECLARE
    v_reservation inventory.reservations%ROWTYPE;
    v_updated_reservation inventory.reservations%ROWTYPE;

    v_quantity_on_hand integer;
    v_quantity_reserved integer;
BEGIN
    /*
     * Validate the request.
     */
    IF p_reservation_id IS NULL THEN
        RAISE EXCEPTION
            'reservation_id is required'
            USING ERRCODE = '22004';
    END IF;

    IF p_reservation_id <= 0 THEN
        RAISE EXCEPTION
            'reservation_id must be greater than zero'
            USING ERRCODE = '22023';
    END IF;

    IF p_reason IS NOT NULL
       AND btrim(p_reason) = '' THEN
        RAISE EXCEPTION
            'reason cannot be blank when supplied'
            USING ERRCODE = '22023';
    END IF;

    /*
     * Lock the reservation so it cannot be fulfilled, released,
     * cancelled, expired, or adjusted by another session at the same time.
     */
    SELECT *
    INTO v_reservation
    FROM inventory.reservations
    WHERE reservation_id = p_reservation_id
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION
            'Reservation % does not exist',
            p_reservation_id
            USING ERRCODE = 'P0002';
    END IF;

    IF v_reservation.status_code <> 'active' THEN
        RAISE EXCEPTION
            'Reservation % cannot be fulfilled because its current status is %',
            p_reservation_id,
            v_reservation.status_code
            USING ERRCODE = 'P0001';
    END IF;

    /*
     * Lock the inventory balance associated with this reservation.
     */
    SELECT
        quantity_on_hand,
        quantity_reserved
    INTO
        v_quantity_on_hand,
        v_quantity_reserved
    FROM public.warehouse_inventory
    WHERE warehouse_inventory_id =
        v_reservation.warehouse_inventory_id
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION
            'Warehouse inventory record % does not exist',
            v_reservation.warehouse_inventory_id
            USING ERRCODE = 'P0002';
    END IF;

    /*
     * Protect against balance drift or uncontrolled direct updates.
     */
    IF v_quantity_reserved < v_reservation.quantity THEN
        RAISE EXCEPTION
            'Reserved inventory balance is inconsistent for warehouse_inventory_id %. Balance: %, reservation quantity: %',
            v_reservation.warehouse_inventory_id,
            v_quantity_reserved,
            v_reservation.quantity
            USING ERRCODE = 'P0001';
    END IF;

    IF v_quantity_on_hand < v_reservation.quantity THEN
        RAISE EXCEPTION
            'On-hand inventory balance is inconsistent for warehouse_inventory_id %. On hand: %, reservation quantity: %',
            v_reservation.warehouse_inventory_id,
            v_quantity_on_hand,
            v_reservation.quantity
            USING ERRCODE = 'P0001';
    END IF;

    /*
     * Consume the physical stock and clear the reserved balance.
     */
    UPDATE public.warehouse_inventory
    SET
        quantity_on_hand =
            quantity_on_hand - v_reservation.quantity,
        quantity_reserved =
            quantity_reserved - v_reservation.quantity,
        updated_at = CURRENT_TIMESTAMP
    WHERE warehouse_inventory_id =
        v_reservation.warehouse_inventory_id;

    /*
     * Move the reservation into its terminal fulfilled state.
     */
    UPDATE inventory.reservations
    SET
        status_code = 'fulfilled',
        fulfilled_at = CURRENT_TIMESTAMP,
        updated_at = CURRENT_TIMESTAMP
    WHERE reservation_id = p_reservation_id
    RETURNING *
    INTO v_updated_reservation;

    /*
     * Append the audit event.
     */
    INSERT INTO inventory.reservation_events (
        reservation_id,
        event_type,
        previous_status_code,
        new_status_code,
        previous_quantity,
        new_quantity,
        reason,
        metadata,
        performed_by_user_id
    )
    VALUES (
        p_reservation_id,
        'fulfilled',
        'active',
        'fulfilled',
        v_reservation.quantity,
        v_reservation.quantity,
        p_reason,
        p_metadata,
        p_performed_by_user_id
    );

    RETURN v_updated_reservation;
END;
$$;

COMMIT;
---------------------------------------------------
-----------005i_adjust_reservation_function
---------------------------------------------------

BEGIN;

CREATE OR REPLACE FUNCTION inventory.adjust_reservation(
    p_reservation_id bigint,
    p_new_quantity integer,
    p_performed_by_user_id integer DEFAULT NULL,
    p_reason text DEFAULT NULL,
    p_metadata jsonb DEFAULT NULL
)
RETURNS inventory.reservations
LANGUAGE plpgsql
AS $$
DECLARE
    v_reservation inventory.reservations%ROWTYPE;
    v_updated_reservation inventory.reservations%ROWTYPE;

    v_quantity_on_hand integer;
    v_quantity_reserved integer;
    v_quantity_available integer;
    v_quantity_difference integer;
BEGIN
    /*
     * Validate the request.
     */
    IF p_reservation_id IS NULL THEN
        RAISE EXCEPTION
            'reservation_id is required'
            USING ERRCODE = '22004';
    END IF;

    IF p_reservation_id <= 0 THEN
        RAISE EXCEPTION
            'reservation_id must be greater than zero'
            USING ERRCODE = '22023';
    END IF;

    IF p_new_quantity IS NULL OR p_new_quantity <= 0 THEN
        RAISE EXCEPTION
            'New reservation quantity must be greater than zero'
            USING ERRCODE = '22023';
    END IF;

    IF p_reason IS NOT NULL
       AND btrim(p_reason) = '' THEN
        RAISE EXCEPTION
            'reason cannot be blank when supplied'
            USING ERRCODE = '22023';
    END IF;

    /*
     * Lock the reservation so no other lifecycle operation can modify it
     * during this adjustment.
     */
    SELECT *
    INTO v_reservation
    FROM inventory.reservations
    WHERE reservation_id = p_reservation_id
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION
            'Reservation % does not exist',
            p_reservation_id
            USING ERRCODE = 'P0002';
    END IF;

    IF v_reservation.status_code <> 'active' THEN
        RAISE EXCEPTION
            'Reservation % cannot be adjusted because its current status is %',
            p_reservation_id,
            v_reservation.status_code
            USING ERRCODE = 'P0001';
    END IF;

    IF p_new_quantity = v_reservation.quantity THEN
        RAISE EXCEPTION
            'New quantity must differ from the current reservation quantity of %',
            v_reservation.quantity
            USING ERRCODE = '22023';
    END IF;

    /*
     * Lock the related inventory balance.
     */
    SELECT
        quantity_on_hand,
        quantity_reserved
    INTO
        v_quantity_on_hand,
        v_quantity_reserved
    FROM public.warehouse_inventory
    WHERE warehouse_inventory_id =
        v_reservation.warehouse_inventory_id
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION
            'Warehouse inventory record % does not exist',
            v_reservation.warehouse_inventory_id
            USING ERRCODE = 'P0002';
    END IF;

    /*
     * Confirm the cached reserved balance can account for the existing
     * reservation before modifying it.
     */
    IF v_quantity_reserved < v_reservation.quantity THEN
        RAISE EXCEPTION
            'Reserved inventory balance is inconsistent for warehouse_inventory_id %. Balance: %, reservation quantity: %',
            v_reservation.warehouse_inventory_id,
            v_quantity_reserved,
            v_reservation.quantity
            USING ERRCODE = 'P0001';
    END IF;

    v_quantity_difference :=
        p_new_quantity - v_reservation.quantity;

    /*
     * A positive difference requires additional available inventory.
     * A negative difference releases part of the existing reservation.
     */
    IF v_quantity_difference > 0 THEN
        v_quantity_available :=
            v_quantity_on_hand - v_quantity_reserved;

        IF v_quantity_difference > v_quantity_available THEN
            RAISE EXCEPTION
                'Insufficient inventory to increase reservation %. Additional requested: %, available: %',
                p_reservation_id,
                v_quantity_difference,
                v_quantity_available
                USING ERRCODE = 'P0001';
        END IF;
    END IF;

    /*
     * Apply only the difference to the cached reserved balance.
     *
     * Example:
     * current reservation = 5
     * new reservation     = 8
     * difference          = 3
     */
    UPDATE public.warehouse_inventory
    SET
        quantity_reserved =
            quantity_reserved + v_quantity_difference,
        updated_at = CURRENT_TIMESTAMP
    WHERE warehouse_inventory_id =
        v_reservation.warehouse_inventory_id;

    /*
     * Update the detailed reservation record.
     */
    UPDATE inventory.reservations
    SET
        quantity = p_new_quantity,
        updated_at = CURRENT_TIMESTAMP
    WHERE reservation_id = p_reservation_id
    RETURNING *
    INTO v_updated_reservation;

    /*
     * Append the audit event.
     */
    INSERT INTO inventory.reservation_events (
        reservation_id,
        event_type,
        previous_status_code,
        new_status_code,
        previous_quantity,
        new_quantity,
        reason,
        metadata,
        performed_by_user_id
    )
    VALUES (
        p_reservation_id,
        'quantity_adjusted',
        'active',
        'active',
        v_reservation.quantity,
        p_new_quantity,
        p_reason,
        p_metadata,
        p_performed_by_user_id
    );

    RETURN v_updated_reservation;
END;
$$;

COMMIT;

----------------------------------------------------
----005j_cancel_reservation_function
----------------------------------------------------
BEGIN;

CREATE OR REPLACE FUNCTION inventory.cancel_reservation(
    p_reservation_id bigint,
    p_performed_by_user_id integer DEFAULT NULL,
    p_reason text DEFAULT NULL,
    p_metadata jsonb DEFAULT NULL
)
RETURNS inventory.reservations
LANGUAGE plpgsql
AS $$
DECLARE
    v_reservation inventory.reservations%ROWTYPE;
    v_updated_reservation inventory.reservations%ROWTYPE;
    v_current_quantity_reserved integer;
BEGIN
    IF p_reservation_id IS NULL THEN
        RAISE EXCEPTION
            'reservation_id is required'
            USING ERRCODE = '22004';
    END IF;

    IF p_reservation_id <= 0 THEN
        RAISE EXCEPTION
            'reservation_id must be greater than zero'
            USING ERRCODE = '22023';
    END IF;

    IF p_reason IS NOT NULL
       AND btrim(p_reason) = '' THEN
        RAISE EXCEPTION
            'reason cannot be blank when supplied'
            USING ERRCODE = '22023';
    END IF;

    /*
     * Lock the reservation to prevent another lifecycle operation from
     * changing it at the same time.
     */
    SELECT *
    INTO v_reservation
    FROM inventory.reservations
    WHERE reservation_id = p_reservation_id
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION
            'Reservation % does not exist',
            p_reservation_id
            USING ERRCODE = 'P0002';
    END IF;

    IF v_reservation.status_code <> 'active' THEN
        RAISE EXCEPTION
            'Reservation % cannot be cancelled because its current status is %',
            p_reservation_id,
            v_reservation.status_code
            USING ERRCODE = 'P0001';
    END IF;

    /*
     * Lock the associated inventory row.
     */
    SELECT quantity_reserved
    INTO v_current_quantity_reserved
    FROM public.warehouse_inventory
    WHERE warehouse_inventory_id =
        v_reservation.warehouse_inventory_id
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION
            'Warehouse inventory record % does not exist',
            v_reservation.warehouse_inventory_id
            USING ERRCODE = 'P0002';
    END IF;

    IF v_current_quantity_reserved < v_reservation.quantity THEN
        RAISE EXCEPTION
            'Reserved inventory balance is inconsistent for warehouse_inventory_id %. Balance: %, reservation quantity: %',
            v_reservation.warehouse_inventory_id,
            v_current_quantity_reserved,
            v_reservation.quantity
            USING ERRCODE = 'P0001';
    END IF;

    /*
     * Return the reserved quantity to availability.
     */
    UPDATE public.warehouse_inventory
    SET
        quantity_reserved =
            quantity_reserved - v_reservation.quantity,
        updated_at = CURRENT_TIMESTAMP
    WHERE warehouse_inventory_id =
        v_reservation.warehouse_inventory_id;

    /*
     * Move the reservation into the terminal cancelled state.
     */
    UPDATE inventory.reservations
    SET
        status_code = 'cancelled',
        cancelled_at = CURRENT_TIMESTAMP,
        updated_at = CURRENT_TIMESTAMP
    WHERE reservation_id = p_reservation_id
    RETURNING *
    INTO v_updated_reservation;

    /*
     * Append the cancellation event.
     */
    INSERT INTO inventory.reservation_events (
        reservation_id,
        event_type,
        previous_status_code,
        new_status_code,
        previous_quantity,
        new_quantity,
        reason,
        metadata,
        performed_by_user_id
    )
    VALUES (
        p_reservation_id,
        'cancelled',
        'active',
        'cancelled',
        v_reservation.quantity,
        v_reservation.quantity,
        p_reason,
        p_metadata,
        p_performed_by_user_id
    );

    RETURN v_updated_reservation;
END;
$$;

COMMIT;
-------------------------------------------------
--------005k_expire_reservation_function.sql
-------------------------------------------------
BEGIN;

CREATE OR REPLACE FUNCTION inventory.expire_reservation(
    p_reservation_id bigint,
    p_performed_by_user_id integer DEFAULT NULL,
    p_reason text DEFAULT NULL,
    p_metadata jsonb DEFAULT NULL
)
RETURNS inventory.reservations
LANGUAGE plpgsql
AS $$
DECLARE
    v_reservation inventory.reservations%ROWTYPE;
    v_updated_reservation inventory.reservations%ROWTYPE;
    v_current_quantity_reserved integer;
BEGIN
    IF p_reservation_id IS NULL THEN
        RAISE EXCEPTION
            'reservation_id is required'
            USING ERRCODE = '22004';
    END IF;

    IF p_reservation_id <= 0 THEN
        RAISE EXCEPTION
            'reservation_id must be greater than zero'
            USING ERRCODE = '22023';
    END IF;

    IF p_reason IS NOT NULL
       AND btrim(p_reason) = '' THEN
        RAISE EXCEPTION
            'reason cannot be blank when supplied'
            USING ERRCODE = '22023';
    END IF;

    /*
     * Lock the reservation so no other lifecycle operation can change it
     * while expiration is being processed.
     */
    SELECT *
    INTO v_reservation
    FROM inventory.reservations
    WHERE reservation_id = p_reservation_id
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION
            'Reservation % does not exist',
            p_reservation_id
            USING ERRCODE = 'P0002';
    END IF;

    IF v_reservation.status_code <> 'active' THEN
        RAISE EXCEPTION
            'Reservation % cannot be expired because its current status is %',
            p_reservation_id,
            v_reservation.status_code
            USING ERRCODE = 'P0001';
    END IF;

    IF v_reservation.expires_at IS NULL THEN
        RAISE EXCEPTION
            'Reservation % cannot be expired because expires_at is NULL',
            p_reservation_id
            USING ERRCODE = 'P0001';
    END IF;

    IF v_reservation.expires_at > CURRENT_TIMESTAMP THEN
        RAISE EXCEPTION
            'Reservation % cannot be expired before %. Current timestamp: %',
            p_reservation_id,
            v_reservation.expires_at,
            CURRENT_TIMESTAMP
            USING ERRCODE = 'P0001';
    END IF;

    /*
     * Lock the associated inventory row.
     */
    SELECT quantity_reserved
    INTO v_current_quantity_reserved
    FROM public.warehouse_inventory
    WHERE warehouse_inventory_id =
        v_reservation.warehouse_inventory_id
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION
            'Warehouse inventory record % does not exist',
            v_reservation.warehouse_inventory_id
            USING ERRCODE = 'P0002';
    END IF;

    IF v_current_quantity_reserved < v_reservation.quantity THEN
        RAISE EXCEPTION
            'Reserved inventory balance is inconsistent for warehouse_inventory_id %. Balance: %, reservation quantity: %',
            v_reservation.warehouse_inventory_id,
            v_current_quantity_reserved,
            v_reservation.quantity
            USING ERRCODE = 'P0001';
    END IF;

    /*
     * Return the reserved quantity to availability.
     */
    UPDATE public.warehouse_inventory
    SET
        quantity_reserved =
            quantity_reserved - v_reservation.quantity,
        updated_at = CURRENT_TIMESTAMP
    WHERE warehouse_inventory_id =
        v_reservation.warehouse_inventory_id;

    /*
     * Move the reservation into the terminal expired state.
     */
    UPDATE inventory.reservations
    SET
        status_code = 'expired',
        expired_at = CURRENT_TIMESTAMP,
        updated_at = CURRENT_TIMESTAMP
    WHERE reservation_id = p_reservation_id
    RETURNING *
    INTO v_updated_reservation;

    /*
     * Append the expiration event.
     */
    INSERT INTO inventory.reservation_events (
        reservation_id,
        event_type,
        previous_status_code,
        new_status_code,
        previous_quantity,
        new_quantity,
        reason,
        metadata,
        performed_by_user_id
    )
    VALUES (
        p_reservation_id,
        'expired',
        'active',
        'expired',
        v_reservation.quantity,
        v_reservation.quantity,
        p_reason,
        p_metadata,
        p_performed_by_user_id
    );

    RETURN v_updated_reservation;
END;
$$;

COMMIT;
----------------------------------------------------------
--------005l_create_reservation_reconciliation_view
----------------------------------------------------------

BEGIN;

CREATE OR REPLACE VIEW inventory.reservation_reconciliation AS
SELECT
    wi.warehouse_inventory_id,
    wi.warehouse_id,
    wi.variant_id,
    wi.quantity_on_hand,
    wi.quantity_reserved AS cached_quantity_reserved,

    COALESCE(
        SUM(r.quantity) FILTER (
            WHERE r.status_code = 'active'
        ),
        0
    )::integer AS calculated_quantity_reserved,

    wi.quantity_reserved
    -
    COALESCE(
        SUM(r.quantity) FILTER (
            WHERE r.status_code = 'active'
        ),
        0
    )::integer AS reserved_quantity_difference,

    wi.quantity_on_hand - wi.quantity_reserved
        AS cached_quantity_available,

    wi.quantity_on_hand
    -
    COALESCE(
        SUM(r.quantity) FILTER (
            WHERE r.status_code = 'active'
        ),
        0
    )::integer AS calculated_quantity_available,

    (
        wi.quantity_reserved
        =
        COALESCE(
            SUM(r.quantity) FILTER (
                WHERE r.status_code = 'active'
            ),
            0
        )::integer
    ) AS is_reconciled

FROM public.warehouse_inventory AS wi

LEFT JOIN inventory.reservations AS r
    ON r.warehouse_inventory_id =
       wi.warehouse_inventory_id

GROUP BY
    wi.warehouse_inventory_id,
    wi.warehouse_id,
    wi.variant_id,
    wi.quantity_on_hand,
    wi.quantity_reserved;

COMMIT;

--------------------------------------------------
-----005m_create_reservation_integrity_check
--------------------------------------------------
BEGIN;

CREATE OR REPLACE FUNCTION inventory.assert_reservation_integrity()
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
    v_mismatch_count integer;
    v_negative_available_count integer;
    v_invalid_terminal_count integer;
BEGIN
    /*
     * Check cached reserved balances against active reservation totals.
     */
    SELECT COUNT(*)
    INTO v_mismatch_count
    FROM inventory.reservation_reconciliation
    WHERE is_reconciled = false;

    IF v_mismatch_count > 0 THEN
        RAISE EXCEPTION
            'Reservation integrity check failed: % warehouse inventory balance(s) are not reconciled',
            v_mismatch_count
            USING ERRCODE = 'P0001';
    END IF;

    /*
     * Available inventory must never be negative.
     */
    SELECT COUNT(*)
    INTO v_negative_available_count
    FROM public.warehouse_inventory
    WHERE quantity_on_hand - quantity_reserved < 0;

    IF v_negative_available_count > 0 THEN
        RAISE EXCEPTION
            'Reservation integrity check failed: % warehouse inventory row(s) have negative availability',
            v_negative_available_count
            USING ERRCODE = 'P0001';
    END IF;

    /*
     * Terminal reservations must have exactly the matching terminal
     * timestamp populated.
     */
    SELECT COUNT(*)
    INTO v_invalid_terminal_count
    FROM inventory.reservations
    WHERE
        (
            status_code = 'fulfilled'
            AND fulfilled_at IS NULL
        )
        OR
        (
            status_code = 'released'
            AND released_at IS NULL
        )
        OR
        (
            status_code = 'cancelled'
            AND cancelled_at IS NULL
        )
        OR
        (
            status_code = 'expired'
            AND expired_at IS NULL
        )
        OR
        (
            status_code = 'active'
            AND num_nonnulls(
                fulfilled_at,
                released_at,
                cancelled_at,
                expired_at
            ) <> 0
        );

    IF v_invalid_terminal_count > 0 THEN
        RAISE EXCEPTION
            'Reservation integrity check failed: % reservation row(s) have invalid status timestamps',
            v_invalid_terminal_count
            USING ERRCODE = 'P0001';
    END IF;

    RAISE NOTICE
        'Reservation integrity check passed.';
END;
$$;

COMMIT;
------------------------------------------------